version: '3'
networks:
  umerun-resume-network:
    driver: bridge
services:
  db:
    container_name: umerun_resume_local_db
    image: mysql:8.0.20
    networks:
      - umerun-resume-network
    ports:
      - 3306:3306
    volumes:
      - .conf/conf.d:/etc/mysql/conf.d
    environment:
      MYSQL_DATABASE: umerun_resume_local
      MYSQL_ROOT_PASSWORD: password
  butler:
    build:
      context: .
      dockerfile: Dockerfile.local
    networks:
      - umerun-resume-network
    volumes:
      - .:/go/src/app
    env_file:
      - .env
    environment:
      APP_SERVICE: batch
      APP_BATCH_TYPE: butler
      DB_HOST: db
    # volumes:
    #   - ./go/src/github.com/Motoyui-inc/rechub-search-server
    depends_on:
      - db
    command: go run main.go
