name: Go
on:
  push:
    branches: 
      - 'issues/*'
      - 'feature/*'
      - 'fix/*'
jobs:

  build:
    name: Test
    runs-on: ubuntu-latest
    steps:

    - uses: mirromutth/mysql-action@v1.1
      with:
        character set server: 'utf8mb4'
        collation server: 'utf8mb4_general_ci'
        mysql version: '8.0.20'
        mysql database: 'rechub_test'
        mysql root password: 'password'

    - name: Set up Go 1.18
      uses: actions/setup-go@v1
      with:
        go-version: 1.18
      id: go

    - name: Check out code into the Go module directory
      uses: actions/checkout@v1
      
    - name: Cache
      uses: actions/cache@v1
      with:
        path: ~/go/pkg/mod
        key: ${{ runner.os }}-go-${{ hashFiles('**/go.sum') }}
        restore-keys: |
          ${{ runner.os }}-go-
          
    - name: Download modules
      # キャッシュが保存されていればそれを使う
      if: steps.cache.outputs.cache-hit != 'true'
      run: go mod download

    # - name: Test
    #   run: |
    #     echo ${{ secrets.ENV_FILE }} | base64 --decode > .env
    #     GOBIN=$(pwd)/bin go install github.com/joho/godotenv/cmd/godotenv
    #     export PATH=$PATH:$(go env GOPATH)/bin
    #     go install github.com/golang/mock/mockgen
    #     bin/godotenv -f ./.env make test-all
